"""Script Generator — produces runnable Python files from OperationLog + AI code.

Takes an OperationLog JSON + AI-generated Python code, wraps them in a
complete script with logging, error handling, structured JSON output,
and a proper entry point.
"""

import ast
import json
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class GenerationConfig:
    """Configuration for script generation."""

    template_dir: str = ""
    python_path: str = "python3"
    include_logging: bool = True
    include_error_handling: bool = True
    include_screenshot_capture: bool = True
    output_json: bool = True


class ScriptGenerator:
    """Generates runnable Python scripts from OperationLog + AI code."""

    def __init__(self, config: GenerationConfig | None = None):
        self.config = config or GenerationConfig()

    def generate(
        self,
        operation_log: dict[str, Any],
        ai_code: str,
    ) -> str:
        """Generate a complete runnable Python script.

        Args:
            operation_log: The OperationLog JSON dict with steps, source, etc.
            ai_code: AI-generated Python code to embed.

        Returns:
            Complete Python script as a string.
        """
        source = operation_log.get("source", "browser")
        operation_id = operation_log.get("id", "unknown")
        task_id = operation_log.get("taskId", "unknown")
        steps = operation_log.get("steps", [])

        lines: list[str] = []

        # ── Shebang + encoding ────────────────────────────────────
        lines.append("#!/usr/bin/env python3")
        lines.append("# -*- coding: utf-8 -*-")
        lines.append("")

        # ── Module docstring ──────────────────────────────────────
        lines.append('"""')
        lines.append(f"Aegis Auto-generated script for task {task_id}")
        lines.append(f"Source: {source} | Operations: {len(steps)} steps")
        lines.append(f"Generated by Aegis Agent Python Runtime")
        lines.append('"""')
        lines.append("")

        # ── Imports ───────────────────────────────────────────────
        lines.append("import json")
        lines.append("import sys")
        lines.append("import traceback")
        if self.config.include_logging:
            lines.append("import logging")
        lines.append("")

        # ── Logging setup ─────────────────────────────────────────
        if self.config.include_logging:
            lines.append("logging.basicConfig(")
            lines.append("    level=logging.INFO,")
            lines.append('    format="%(asctime)s [%(levelname)s] %(message)s"')
            lines.append(")")
            lines.append("logger = logging.getLogger(__name__)")
            lines.append("")

        # ── Structured output helper ──────────────────────────────
        if self.config.output_json:
            lines.append("def emit_result(operation_id: str, status: str, data: dict = None, error: str = None):")
            lines.append('    """Output structured JSON result for the TypeScript executor."""')
            lines.append("    result = {")
            lines.append('        "operation_id": operation_id,')
            lines.append('        "status": status,')
            lines.append('        "timestamp": __import__("datetime").datetime.utcnow().isoformat() + "Z",')
            lines.append("    }")
            lines.append("    if data is not None:")
            lines.append('        result["data"] = data')
            lines.append("    if error is not None:")
            lines.append('        result["error"] = error')
            lines.append("    print(json.dumps(result))")
            lines.append("")

        # ── Screenshot capture helper ─────────────────────────────
        if self.config.include_screenshot_capture and source == "browser":
            lines.append("def capture_screenshot(page, name: str = 'screenshot'):")
            lines.append('    """Capture a screenshot from a Playwright page."""')
            lines.append("    path = f'{name}.png'")
            lines.append("    page.screenshot(path=path)")
            lines.append('    logger.info(f"Screenshot saved: {path}")')
            lines.append("    return path")
            lines.append("")

        # ── Main function ─────────────────────────────────────────
        if self.config.include_error_handling:
            lines.append("def main():")
            lines.append(f'    """Execute automation for operation {operation_id}."""')
            if self.config.include_logging:
                lines.append(f'    logger.info("Starting operation {operation_id} ({source})")')
            lines.append("    try:")
        else:
            lines.append("def main():")

        # ── AI-generated code (indented under try/main) ───────────
        indent = "        " if self.config.include_error_handling else "    "
        if ai_code.strip():
            for code_line in ai_code.rstrip("\n").split("\n"):
                lines.append(f"{indent}{code_line}")
        else:
            lines.append(f"{indent}pass  # No AI code provided")

        # ── Success output ────────────────────────────────────────
        if self.config.output_json:
            lines.append(f"{indent}emit_result('{operation_id}', 'completed', {{'steps': {len(steps)}}})")
        elif self.config.include_logging:
            lines.append(f'{indent}logger.info("Operation completed successfully")')

        # ── Exception handling ────────────────────────────────────
        if self.config.include_error_handling:
            lines.append("    except Exception as e:")
            if self.config.include_logging:
                lines.append('        logger.error(f"Operation failed: {e}")')
                lines.append("        traceback.print_exc()")
            if self.config.output_json:
                lines.append(f"        emit_result('{operation_id}', 'failed', error=str(e))")
            lines.append("        sys.exit(1)")

        lines.append("")

        # ── Entry point ───────────────────────────────────────────
        lines.append('if __name__ == "__main__":')
        lines.append(f"    # Entry point for {operation_id}")
        lines.append("    main()")

        return "\n".join(lines) + "\n"

    def generate_requirements(
        self,
        source: str = "browser",
        extra_deps: list[str] | None = None,
        pin_versions: bool = False,
    ) -> str:
        """Generate a requirements.txt content string.

        Args:
            source: Operation source ('browser' or 'desktop').
            extra_deps: Additional pip package names to include.
            pin_versions: Whether to pin minimum versions.

        Returns:
            Requirements text, one package per line.
        """
        packages: list[str] = []

        if source == "browser":
            if pin_versions:
                packages.append("playwright>=1.40.0")
            else:
                packages.append("playwright")
        elif source == "desktop":
            if pin_versions:
                packages.append("pyautogui>=0.9.54")
            else:
                packages.append("pyautogui")

        if extra_deps:
            for dep in extra_deps:
                if pin_versions and ">=" not in dep and "==" not in dep:
                    packages.append(f"{dep}>=0.0.0")
                else:
                    packages.append(dep)

        # Deduplicate while preserving order
        seen: set[str] = set()
        unique: list[str] = []
        for pkg in packages:
            name = pkg.split(">=")[0].split("==")[0].strip()
            if name not in seen:
                seen.add(name)
                unique.append(pkg)

        return "\n".join(unique)
